version: '3.9'
services:
  node_service:
    container_name: node-server
    # depends_on:
    #   - db
    build: .
    image: tracker/node
    env_file: ./.env
    volumes:
      - ./src:/app/src
    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - MYSQL_HOST=db
    stdin_open: true
    tty: true
  # db:
    # image: mysql:latest
    # container_name: db
    # ports:
      # - $MYSQL_PORT:$MYSQL_PORT
    # volumes:
      # - db:/var/lib/mysql
    # env_file: .env
    # environment:
      # MYSQL_DATABASE: $MYSQL_DATABASE
      # MYSQL_USER: $MYSQL_USER
      # MYSQL_PASSWORD: $MYSQL_USER_PASSWORD
      # MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    # command: --default-authentication-plugin=mysql_native_password
    # restart: unless-stopped
# volumes:
  # db: